### ISSUE TITLE
Pixelation

### ISSUE THREAD

**Issue by stalgiag** [stalgiag/p5.xr#19]
View is much more pixelated than is logical. Seems to be some odd upscaling. Not sure requires further investigation.

**Comment by stalgiag** [comment]
and in a comical update, I now realize that the two XRViews are rendering at 150x300 each

**Comment by stalgiag** [comment]
closed [with #b323016](https://github.com/stalgiag/p5.xr/commit/b323016d2baeac8527da551742c8ad0099e1cdc8)

**Comment by stalgiag** [comment]
reopened with #23

**Comment by vedhant** [comment]
> and in a comical update, I now realize that the two XRViews are rendering at 150x300 each

Yes, even I am getting 150x300 resolution for the two XRViews.
In fact, when I close the VR session and re run it by clicking "Enter VR" the resolution of XRViews changes to 858x858 and the resulting view is not pixelated.

I want to know on which canvas does webxr exactly render to. Does it use p5's canvas or does it use its own canvas for rendering VR?  I'm doubtful because p5's canvas width is 100.

**Comment by vedhant** [comment]
I did some digging in and found some interesting stuff which actually fixes this issue.

Firstly, when the "Enter VR" button is clicked ```p5._setup()``` is run twice instead of once.
 
```javascript
this.startSketch = function(session) {
  self.xrSession = self.xrButton.session = session;
  self.xrSession.addEventListener('end', self.onSessionEnded);
// FIRST time here
  self.preloadOverride();
  // create p5 canvas
  createCanvas(windowWidth, windowHeight, WEBGL);
  if(self.injectedPolyfill) {
    self.onRequestSessionPolyfill();
  } else {
    self.onRequestSessionNoPF();
  }
// SECOND time here
  p5.instance._decrementPreload();
};
```
```preloadOverride()``` and ```_decrementPreload()``` (calls ```_runIfPreloadsAreDone()```) both call ```_setup()```.

Now, ```_setup()``` creates a new 100x100 p2d canvas and replaces previously created canvases. Because of this, in the above code canvas created by ```p5.instance._decrementPreload();``` replaces canvas created by ```createCanvas(windowWidth, windowHeight, WEBGL);```. This is the issue lying behind pixelation. When I removed the creation of default p2d canvas from ```_setup()```, there was no pixelation and everything rendered perfectly.

There is no reason for ```_setup``` to create a canvas as p5xr will make sure the creation of WebGL canvas. So, I think we should have to replace ```_setup()``` in p5 by a custom function ```_setupxr()``` which does not create any canvas.

Also, ```_setup()``` is been called twice which means the ```setup()``` in user code will also run twice. This is undesirable and should not happen. @stalgiag I think we should modify ```_runIfPreloadsAreDone()``` so that it does not run ```_setup()``` (as it is already run in ```preloadOverride()```) and ```_draw()``` (I think its unnecessary to call it).

**Comment by stalgiag** [comment]
Good catch @vedhant! I should've remembered that 100x100 is the default p5 canvas size. I think the `_setupxr` idea is a good one, and that should be simple enough to handle by doing something similar to `_updatexr`.

Regarding the fact that `_setup` is run twice, if I am following correctly, perhaps we can just ignore `preloadOverride()`? I don't want to modify any p5 prototypes.

**Comment by vedhant** [comment]
Removing ```preloadOverride()``` produces error : 
Uncaught TypeError: Cannot read property 'set' of undefined
    at onXRFrame

However moving ```p5.instance._decrementPreload();``` from bottom to ```self.preloadOverride();``` will work fine.
```javascript
this.startSketch = function(session) {
  self.xrSession = self.xrButton.session = session;
  self.xrSession.addEventListener('end', self.onSessionEnded);
  p5.instance._decrementPreload();
  // create p5 canvas
  createCanvas(windowWidth, windowHeight, WEBGL);
  if(self.injectedPolyfill) {
    self.onRequestSessionPolyfill();
  } else {
    self.onRequestSessionNoPF();
  }
};
```

**Comment by stalgiag** [comment]
Cool so then that plus `_setupxr` should provide a fix
